spring.application.name=resumefit
spring.datasource.url=jdbc:postgresql://localhost:5432/resumefit
spring.datasource.username=postgres
spring.datasource.password=Yamunakota_53

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true